function mask = get_mask(current_node,...
                        tentative_nodes,...
                        num_nodes,...
                        num_plane,...
                        num_x,...
                        test_mat)


mask = (tentative_nodes > 0 & tentative_nodes < num_nodes+1)...
    & (((current_node-num_plane>0) & test_mat(:,1))...
    | ((((mod(current_node,num_plane) == 0) | (mod(current_node,num_plane) > mod(current_node - num_x,num_plane))) & (mod(current_node - num_x,num_plane) ~= 0)) & test_mat(:,2))...
    | ((mod(current_node-1,num_x) > 0) & test_mat(:,3))...
    | ((mod(current_node+1,num_x) ~= 1) & test_mat(:,4))...
    | (((mod(current_node,num_plane) ~=0) & ((mod(current_node,num_plane) < mod(current_node + num_x,num_plane)) | (mod(current_node + num_x,num_plane)==0))) & test_mat(:,5))...
    | (((current_node+num_plane)<(num_nodes+1)) & test_mat(:,6)));